import React, { useState, useRef } from 'react';
import { Eye, Upload, User, LogOut, Loader2, Info, X } from 'lucide-react';
import toast from 'react-hot-toast';
import Profile from './Profile';
import './Dashboard.css';
import api from "../api";

const Dashboard = ({ setAuth }) => {
  const [preview, setPreview] = useState(null);
  const [showMenu, setShowMenu] = useState(false);
  const [showProfile, setShowProfile] = useState(false);
  const [showInfoModal, setShowInfoModal] = useState(false);
  const inputRef = useRef(null);

  const [selectedFile, setSelectedFile] = useState(null);
  const [result, setResult] = useState(null);
  const [isUploading, setIsUploading] = useState(false);
  const [heatmapUrl, setHeatmapUrl] = useState(null);
  const [isHeatmapLoading, setIsHeatmapLoading] = useState(false);
  const [showHeatmapModal, setShowHeatmapModal] = useState(false);

  const uploadToServer = async (file) => {
    const fd = new FormData();
    fd.append("file", file);

    const res = await api.post("/upload", fd, {
      headers: { "Content-Type": "multipart/form-data" },
    });

    setResult({
      scanId: res.data.scan_id,
      status: res.data.status,
      filename: res.data.filename,
      isSafe: res.data.is_safe,
      vtMessage: res.data.vt_message,
      metadata: res.data.metadata,
      confidence: res.data.confidence, 
      aiPrediction: res.data.ai_prediction, 
      fileHash: res.data.file_hash 
    });
  };

  const handleUpload = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setShowMenu(false);
    setResult(null);
    setSelectedFile(file);

    // תצוגה מקדימה של התמונה
    const reader = new FileReader();
    reader.onload = () => setPreview(reader.result);
    reader.readAsDataURL(file);

    // הפעלת ההעלאה עם מעקב של Toast
    const uploadPromise = uploadToServer(file);

    toast.promise(uploadPromise, {
      loading: 'Uploading and analyzing image...',
      success: 'Analysis complete!',
      error: (err) => err?.response?.data?.error || 'Error uploading image'
    });

    try {
      setIsUploading(true);
      await uploadPromise;
    } catch (err) {
      // ניקוי במקרה של שגיאה
      setPreview(null);
      setSelectedFile(null);
      if (inputRef.current) inputRef.current.value = "";
    } finally {
      setIsUploading(false);
    }
  };

  const handleReset = () => {
    setPreview(null);
    setSelectedFile(null);
    setResult(null);
    setHeatmapUrl(null);
    setShowHeatmapModal(false);
    if (inputRef.current) inputRef.current.value = "";
  };

  const handleLogout = () => {
    localStorage.removeItem("access_token");
    localStorage.removeItem("currentUser");
    setAuth(false);
    toast.success('Logged out successfully 👋');
  };

  if (showProfile) {
    return <Profile setAuth={setAuth} onBack={() => setShowProfile(false)} />;
  }

  const handleViewHeatmap = async () => {
    if (!result?.scanId) return;

    try {
      setIsHeatmapLoading(true);

      // אם כבר נוצר Heatmap קודם, לא צריך לבקש שוב מהשרת
      if (heatmapUrl) {
        setShowHeatmapModal(true);
        return;
      }

      const res = await api.get(`/upload/heatmap/${result.scanId}`, {
        responseType: "blob",
      });

      const imageUrl = URL.createObjectURL(res.data);
      setHeatmapUrl(imageUrl);
      setShowHeatmapModal(true);

      toast.success("Heatmap generated successfully!");
    } catch (err) {
      toast.error(err?.response?.data?.error || "Failed to generate heatmap");
    } finally {
      setIsHeatmapLoading(false);
    }
  };

  return (
    <div className="dashboard">

{/* כפתור המידע המרחף - מחוץ לריבוע העלאה */}
      <button className="info-floating-btn" onClick={() => setShowInfoModal(true)}>
        <Info size={24} />
      </button>

      {/* חלון המידע (Modal) */}
      {showInfoModal && (
        <div className="info-overlay" onClick={() => setShowInfoModal(false)}>
          <div className="info-modal fade-up" onClick={(e) => e.stopPropagation()}>
            <div className="info-modal-header">
              <h3>System Guide</h3>
              <button className="close-info-btn" onClick={() => setShowInfoModal(false)}>
                <X size={20} />
              </button>
            </div>
            <div className="info-modal-body">
              <div className="info-item">
                <h4>🛡️ VirusTotal Scan</h4>
                <p>Before analysis, we scan the file against 70+ antivirus engines. This ensures the file is safe to process and hasn't been tampered with by malware.</p>
              </div>
              <div className="info-item">
                <h4>🧠 Model Confidence</h4>
                <p>The probability score generated by our Deepfake model. High confidence means our Model is very certain about its authenticity decision.</p>
              </div>
              <div className="info-item">
                <h4>📍 Forensic Metadata</h4>
                <p style={{ marginBottom: '0.5rem', fontSize: '0.75rem' }}>Digital footprints found in the file:</p>
                
                <div className="metadata-guide-grid">
                  <div className="guide-entry">
                    <strong>Format:</strong>
                    <span>File type (JPEG, PNG).</span>
                  </div>
                  <div className="guide-entry">
                    <strong>Model:</strong>
                    <span>The capture device.</span>
                  </div>
                  <div className="guide-entry">
                    <strong>Software:</strong>
                    <span>OS or editing tools.</span>
                  </div>
                  <div className="guide-entry">
                    <strong>Resizing:</strong>
                    <span>Crop/Size changes.</span>
                  </div>
                  <div className="guide-entry">
                    <strong>Timestamp:</strong>
                    <span>Date & time of capture.</span>
                  </div>
                  <div className="guide-entry">
                    <strong>Location:</strong>
                    <span>City and Country info.</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {showHeatmapModal && heatmapUrl && (
        <div className="heatmap-overlay" onClick={() => setShowHeatmapModal(false)}>
          <div className="heatmap-modal fade-up" onClick={(e) => e.stopPropagation()}>
            
            <div className="heatmap-modal-header">
              <div className="heatmap-title-group">
                <h3>Model Heatmap</h3>
                <p>
                  The highlighted regions show which areas most influenced the model’s decision.
                </p>
              </div>

              <button
                className="close-heatmap-btn"
                onClick={() => setShowHeatmapModal(false)}
                aria-label="Close heatmap"
              >
                <X size={15} />
              </button>
            </div>

            <div className="heatmap-modal-body">
              <img
                src={heatmapUrl}
                alt="Model heatmap"
                className="heatmap-image"
              />
            </div>

            <div className="heatmap-legend">
              <div className="heatmap-legend-bar"></div>

              <div className="heatmap-legend-labels">
                <span>Low influence</span>
                <span>Medium</span>
                <span>High influence</span>
              </div>

              <div className="heatmap-legend-notes">
                <div className="legend-note">
                  <span className="legend-dot blue"></span>
                  <span>Cool colors = weaker influence</span>
                </div>
                <div className="legend-note">
                  <span className="legend-dot red"></span>
                  <span>Warm colors = stronger influence</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ===== TOP BAR ===== */}
      <header className="topbar">
        <div className="logo">
          <div className="logo-icon">
            <Eye size={18} />
          </div>
          <span className="logo-text">RealEyes</span>
        </div>

        <div className="profile">
          <button className="profile-btn" onClick={() => setShowMenu(!showMenu)}>
            <User size={18} />
          </button>

          {showMenu && (
            <div className="profile-menu">
              <button onClick={() => {
                setShowProfile(true);  
                setShowMenu(false);
              }}>
              <User size={16} />
                My Profile
              </button>

              <button onClick={handleLogout}>
                <LogOut size={16} />
                Logout
              </button>
            </div>
          )}
        </div>
      </header>

      {/* ===== MAIN ===== */}
      <main className="content">
        <h1 className="title">Deepfake Image Analysis</h1>
        <p className="subtitle">
        Deepfake Image Detection System
        </p>

        <div 
          className={`upload-card ${preview ? 'expanded' : ''}`}
          onDragOver={(e) => e.preventDefault()}
          onDrop={async (e) => {
            e.preventDefault();
            const file = e.dataTransfer.files?.[0];
            if (!file || !file.type.startsWith('image/')) return;

            setShowMenu(false);
            setResult(null);
            setSelectedFile(file);

            // תצוגה מקדימה של התמונה הנגררת
            const reader = new FileReader();
            reader.onload = () => setPreview(reader.result);
            reader.readAsDataURL(file);

            // הפעלת ההעלאה לשרת
            const uploadPromise = uploadToServer(file);

            toast.promise(uploadPromise, {
              loading: 'Uploading and analyzing image...',
              success: 'Analysis complete!',
              error: (err) => err?.response?.data?.error || 'Error uploading image'
            });

            try {
              setIsUploading(true);
              await uploadPromise;
            } catch (err) {
              setPreview(null);
              setSelectedFile(null);
              if (inputRef.current) inputRef.current.value = "";
            } finally {
              setIsUploading(false);
            }
          }}
        >

          {/* אזור תמונה */}
          <div className={`image-area ${result ? 'shrink' : ''}`}>    
            {!preview ? (
              <>
                <input
                  ref={inputRef}
                  type="file"
                  accept="image/*"
                  hidden
                  onChange={handleUpload}
                />
                <button
                  className="upload-btn"
                  onClick={() => inputRef.current.click()}
                >
                  <Upload size={18} />
                  Upload Image
                </button>
              </>
            ) : (
              <img src={preview} alt="preview" className="image-preview" />
            )}
          </div>

        {/* אזור המתנה/ניתוח */}
          {preview && !result && isUploading && (
            <div className="analysis-loading">
                <Loader2 className="spinner-icon" size={40} />
                <p>Analyzing Image...</p>
            </div>
          )}

          {/* תוצאות */}
          {/* {result && (
            <div className="results-container">
                <div className={`result-box ${result.isFake ? 'fake' : 'real'}`}>
                <h3>
                    {result.isFake ? 'Fake Detected' : 'Image Appears Real'}
                </h3>
                <p>Confidence: {result.confidence}%</p>

                <div className="result-actions">
                    <button className="secondary-btn">Download Report</button>
                    <button className="secondary-btn">View Heatmap</button>
                </div>
                
                </div> */}

                {/* כפתור העלאה מחדש - קטן ומתחת לתוצאות */}
                {/* <button className="reupload-link" onClick={handleReset}>
                    <Upload size={14} />
                    Upload Another Image
                </button>
            </div> */}
          {/* )} */}

        {/* תוצאות */}
          {result && (
            <div className="results-container">
                <div className={`result-box ${!result.isSafe ? 'fake' : (result.aiPrediction === 'FAKE' ? 'fake' : 'real')}`}>                    
                
 {/* כותרת */}
                {!result.isSafe ? (
                    <h3>Warning: Malicious File</h3>
                ) : result.aiPrediction === 'ERROR' ? (
                    <h3 style={{ color: '#f59e0b', fontSize: '1.2rem', fontWeight: 'bold' }}>
                        Analysis Failed
                    </h3>
                ) : (
                    <h3 style={{ 
                        color: result.aiPrediction === 'FAKE' ? '#ef4444' : '#22c55e', 
                        fontSize: '1.2rem',
                        fontWeight: 'bold'
                    }}>
                        {result.aiPrediction === 'FAKE' ? 'Fake Detected' : 'Image Appears Real'}
                    </h3>
                )}
                
                {/* אחוזי ביטחון מה-DB */}
                <p className="confidence-text">
                    Confidence: {result.confidence === null ? 'N/A' : `${result.confidence}%`}
                </p>

                {/* סטטוס וירוס טוטאל בקטן */}
                <p className="vt-status">
                    VT Status: {result.vtMessage} {result.isSafe}
                </p>
                {result.metadata && Object.keys(result.metadata).length > 0 && (
                  <div style={{ 
                    marginTop: '1.2rem', /* הקטנו מעט את המרווח מלמעלה */
                    textAlign: 'left', 
                    background: 'rgba(15, 23, 42, 0.4)', 
                    padding: '0.8rem 1.2rem 1.2rem', /* הקטנו פדינג עליון כדי שהכותרת תעלה */
                    borderRadius: '12px', 
                    border: '1px solid rgba(255, 255, 255, 0.05)',
                    width: '100%',
                    boxSizing: 'border-box'
                  }}>
                    <p style={{ 
                      fontSize: '0.75rem', 
                      fontWeight: 'bold', 
                      color: '#a78bfa', 
                      marginBottom: '0.6rem', /* הקטנו מרווח כדי שהתוכן יעלה */
                      textTransform: 'uppercase', 
                      textAlign: 'center', 
                      letterSpacing: '1px' 
                    }}>
                        Image Metadata
                    </p>
                    
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px 20px' }}>
                      {Object.entries(result.metadata).map(([key, value]) => (
                        <div key={key} style={{ 
                          display: 'flex', 
                          justifyContent: 'flex-start', /* 🟢 שינוי: הערך נצמד למפתח */
                          gap: '8px',                   /* 🟢 רווח קבוע בין המפתח לערך */
                          fontSize: '0.7rem', 
                          borderBottom: '1px solid rgba(255, 255, 255, 0.05)', 
                          padding: '4px 0' 
                        }}>
                          <span style={{ color: 'rgba(255, 255, 255, 0.4)', fontWeight: '500', minWidth: 'fit-content' }}>
                            {key}:
                          </span>
                          <span style={{ 
                            color: 'rgba(255, 255, 255, 0.9)', 
                            fontWeight: '600'
                          }}>
                            {value}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                <div className="result-actions">
                <button 
                  className="secondary-btn" 
                  disabled={!result.isSafe || result.aiPrediction === 'ERROR' || isHeatmapLoading}
                  onClick={handleViewHeatmap}
                >
                  {isHeatmapLoading ? 'Generating...' : 'View Heatmap'}
                </button>
                </div>
                </div>
                <button className="reupload-link" onClick={handleReset}>
                    <Upload size={14} />
                    Upload Another Image
                </button>
            </div>
          )}

        </div>
      </main>
    </div>
  );
};

export default Dashboard;